#!/bin/sh

readonly DEST_DIR=$HOME
readonly BACK_DIR=$DEST_DIR/.dotfiles.bak
readonly OWD=`pwd`

installdot() {
  local install=$OWD/$1
  echo "==> install .$1"

  if [ ! -e $BACK_DIR ]; then
    echo "$BACK_DIR does not exist!"
    return
  fi

  if [ -e $BACK_DIR/$1 ]; then
    if [ ! -L $DEST_DIR/.$1 ]; then
      echo "Warning: .$1 exists in $BACK_DIR but is not a symlink in $DEST_DIR."
    fi
    return
  fi

  if [ -e $DEST_DIR/.$1 ]; then
    mv $DEST_DIR/.$1 $BACK_DIR
  fi

  ln -s $install $DEST_DIR/.$1
}

if [ ! -d $BACK_DIR ]; then
  mkdir -p $BACK_DIR
fi

echo "==> install base16-shell"
git clone https://github.com/chriskempson/base16-shell.git \
    lib/base16-shell

echo "==> install base16-gnome-terminal"
git clone https://github.com/chriskempson/base16-gnome-terminal.git \
    share/base16-gnome-terminal
echo "==> install base16-xresources"
git clone https://github.com/chriskempson/base16-xresources.git \
    share/base16-xresources
echo "==> install base16-textmate"
git clone https://github.com/chriskempson/base16-textmate.git \
    share/base16-textmate
echo "==> install base16-iterm2"
git clone https://github.com/chriskempson/base16-iterm2.git \
    share/base16-iterm2
echo "==> install powerline-fonts"
git clone https://github.com/Lokaltog/powerline-fonts.git \
    share/powerline-fonts

echo "==> install vundle"
mkdir -p vim/bundle
git clone https://github.com/gmarik/Vundle.vim vim/bundle/Vundle.vim

echo "==> install tpm"
mkdir -p tmux/plugins
git clone https://github.com/tmux-plugins/tpm tmux/plugins/tpm

echo "==> install spacemacs"
git clone --recursive https://github.com/syl20bnr/spacemacs emacs.d

installdot Xresources
installdot bashrc
installdot gdbinit
installdot gitconfig
installdot gitignore_global
installdot inputrc
installdot rcrc
installdot tmux.conf
installdot tmux
installdot emacs.d
installdot vim
installdot vimrc
installdot vimrc.bundles
installdot vimrc.more
installdot zshrc
installdot bin
installdot lib
installdot share
