#!/bin/bash

set -e

readonly DEST_DIR=$HOME
readonly BACK_DIR=$DEST_DIR/.dotfiles-backup
readonly PWD=`pwd`

function installdot {
  local install=$PWD/$1
  echo "==> install .$1"

  if [ ! -e $BACK_DIR ]; then
    echo "$BACK_DIR does not exist!"
    return
  fi

  if [ -e $BACK_DIR/$1 ]; then
    if [ ! -L $DEST_DIR/.$1 ]; then
      echo "Warning: .$1 exists in $BACK_DIR but is not a symlink in $DEST_DIR."
    fi
    return
  fi

  if [ -e $DEST_DIR/.$1 ]; then
    mv $DEST_DIR/.$1 $BACK_DIR
  fi

  ln -s $install $DEST_DIR/.$1
}

function init {
  if [ ! -d $BACK_DIR ]; then
    mkdir -p $BACK_DIR
  fi
}

function install_thirdparty {
  echo "==> install vundle"
  mkdir -p vim/bundle
  rm -rf vim/bundle/Vundle.vim
  git clone https://github.com/gmarik/Vundle.vim vim/bundle/Vundle.vim

  echo "==> install tpm"
  mkdir -p tmux/plugins
  rm -rf tmux/plugins/tpm
  git clone https://github.com/tmux-plugins/tpm tmux/plugins/tpm

  echo "==> install spacemacs"
  rm -rf emacs.d
  git clone --recursive https://github.com/syl20bnr/spacemacs emacs.d

  echo "==> Install wal"
  rm -rf dots/pkg
  git clone https://github.com/dylanaraps/wal.git dots/pkg
}

function gen_fortunes {
  echo "==> generate fortunes"
  pushd dots/fortune > /dev/null
  make
  popd > /dev/null
}

function install_dots {
  installdot dots
  installdot Xresources
  installdot bashrc
  installdot gdbinit
  installdot gitconfig
  installdot gitignore_global
  installdot inputrc
  installdot rcrc
  installdot tmux.conf
  installdot tmux
  installdot emacs.d
  installdot vim
  installdot vimrc
  installdot vimrc.more
  installdot zshrc
  installdot bin
}

function main {
  #init
  #install_thirdparty
  #gen_fortunes
  install_dots
}

main
